//! Cross-validation tests: symplex vs SymPy.
//!
//! Reads fixtures generated by `scripts/generate_sympy_fixtures.py`
//! and verifies that symplex produces numerically equivalent results
//! for differentiation, integration, simplification, expansion,
//! solving, evaluation, and series.

use symplex::prelude::*;

const TOLERANCE: f64 = 1e-6;

#[derive(serde::Deserialize)]
#[allow(dead_code)]
struct FixtureFile {
    generated_by: String,
    fixtures: Vec<Fixture>,
}

#[derive(serde::Deserialize)]
#[allow(dead_code)]
struct Fixture {
    category: String,
    input: Option<String>,
    sympy_result: Option<String>,
    eval_points: Option<Vec<EvalPoint>>,
    sympy_roots: Option<Vec<Root>>,
    value: Option<NumValue>,
}

#[derive(serde::Deserialize)]
#[allow(dead_code)]
struct EvalPoint {
    x: Option<f64>,
    value: Option<NumValue>,
}

#[derive(serde::Deserialize)]
#[allow(dead_code)]
struct NumValue {
    re: f64,
    im: f64,
}

#[derive(serde::Deserialize)]
#[allow(dead_code)]
struct Root {
    symbolic: String,
    re: f64,
    im: f64,
}

fn approx_eq(a: f64, b: f64) -> bool {
    if a.is_nan() && b.is_nan() {
        return true;
    }
    if a.is_infinite() && b.is_infinite() {
        return a.signum() == b.signum();
    }
    (a - b).abs() < TOLERANCE || (a - b).abs() / (a.abs().max(b.abs()).max(1e-15)) < TOLERANCE
}

#[test]
fn cross_validate_against_sympy() {
    let json_str = include_str!("fixtures/sympy_cross_validation.json");
    let file: FixtureFile =
        serde_json::from_str(json_str).expect("Failed to parse sympy fixture JSON");

    println!("Cross-validating against {}", file.generated_by);

    let ctx = Context::new();
    let x_sym = ctx.symbol("x");
    let mut passed = 0;
    let mut failed = 0;
    let mut skipped = 0;

    for fixture in &file.fixtures {
        let input = match &fixture.input {
            Some(s) => s,
            None => {
                skipped += 1;
                continue;
            }
        };

        // Parse the input expression (using our SymPy-compatible parser)
        let expr = match symplex::parse::parse(&ctx, input) {
            Ok(e) => e,
            Err(e) => {
                println!(
                    "  SKIP [{}] parse failed for '{}': {}",
                    fixture.category, input, e
                );
                skipped += 1;
                continue;
            }
        };

        // Apply the operation
        let result = match fixture.category.as_str() {
            "diff" => expr.diff(&x_sym),
            "integrate" => expr.integrate(&x_sym),
            "simplify" => expr.full_simplify(),
            "expand" => {
                if input.contains("sin(") || input.contains("cos(") {
                    expr.expand_trig()
                } else {
                    expr.expand()
                }
            }
            "series" => match expr.maclaurin(&x_sym, 6) {
                Ok(s) => s,
                Err(_) => {
                    skipped += 1;
                    continue;
                }
            },
            "eval" => expr.eval(),
            "solve" => {
                // Solve tests: verify each root satisfies the equation
                let roots = expr.solve_or_empty(&x_sym);
                let sympy_roots = match fixture.sympy_roots.as_ref() {
                    Some(r) => r,
                    None => {
                        skipped += 1;
                        continue;
                    }
                };

                // Every symplex root must be correct
                let mut all_ok = true;
                for root in &roots {
                    let residual = expr.subs(&x_sym, root).evalf_f64();
                    if let Ok(r) = residual {
                        if r.abs() > TOLERANCE {
                            println!(
                                "  FAIL [solve] '{}': root {} has residual {}",
                                input, root, r
                            );
                            all_ok = false;
                        }
                    }
                }
                // Count how many SymPy real roots we found
                let real_sympy_roots: Vec<_> =
                    sympy_roots.iter().filter(|r| r.im.abs() < 1e-10).collect();
                if roots.len() < real_sympy_roots.len() {
                    println!(
                        "  INFO [solve] '{}': symplex found {}/{} real roots",
                        input,
                        roots.len(),
                        real_sympy_roots.len()
                    );
                }
                if all_ok {
                    passed += 1;
                } else {
                    failed += 1;
                }
                continue;
            }
            _ => {
                skipped += 1;
                continue;
            }
        };

        // For eval category with direct value
        if fixture.category == "eval" {
            if let Some(expected) = &fixture.value {
                match result.evalf_f64() {
                    Ok(val) => {
                        if approx_eq(val, expected.re) {
                            passed += 1;
                        } else {
                            println!(
                                "  FAIL [eval] '{}': symplex={}, sympy={}",
                                input, val, expected.re
                            );
                            failed += 1;
                        }
                    }
                    Err(e) => {
                        println!("  SKIP [eval] '{}': evalf failed: {}", input, e);
                        skipped += 1;
                    }
                }
                continue;
            }
        }

        // Numerical comparison at eval points
        if let Some(points) = &fixture.eval_points {
            let mut fixture_ok = true;
            for pt in points {
                let x_val = match pt.x {
                    Some(v) => v,
                    None => continue,
                };
                let expected = match &pt.value {
                    Some(v) => v,
                    None => continue,
                };

                // Substitute and evaluate
                let point_expr = symplex::parse::parse(&ctx, &format!("{}", x_val))
                    .unwrap_or_else(|_| ctx.int(0));
                let evaluated = result.subs(&x_sym, &point_expr).evalf_f64();

                match evaluated {
                    Ok(val) => {
                        if !approx_eq(val, expected.re) {
                            println!(
                                "  FAIL [{}] '{}' at x={}: symplex={}, sympy={}",
                                fixture.category, input, x_val, val, expected.re
                            );
                            fixture_ok = false;
                        }
                    }
                    Err(_) => {
                        // evalf failure — might be a free symbol issue, skip
                    }
                }
            }
            if fixture_ok {
                passed += 1;
            } else {
                failed += 1;
            }
        } else {
            skipped += 1;
        }
    }

    println!("\n=== Cross-validation summary ===");
    println!("Passed:  {passed}");
    println!("Failed:  {failed}");
    println!("Skipped: {skipped}");

    assert_eq!(failed, 0, "{failed} cross-validation fixtures failed");
}
