//! Comprehensive cross-validation: symplex vs SymPy (263 fixtures)
//!
//! Reads fixtures generated by `scripts/generate_sympy_fixtures.py`
//! and verifies that symplex produces numerically equivalent results
//! for ALL 13 categories (37 subcategories, 263 total fixtures):
//!   diff, integrate, definite_integral, simplify, expand, solve,
//!   eval, series, limit, matrix, algebra, evalf, special_func.

use std::collections::HashMap;
use symplex::prelude::*;

const TOLERANCE: f64 = 1e-6;

// ── JSON deserialization structs ───────────────────────────────────────

#[derive(serde::Deserialize)]
struct FixtureFile {
    generated_by: String,
    #[allow(dead_code)]
    generated_at: Option<String>,
    fixture_count: usize,
    fixtures: Vec<Fixture>,
}

#[derive(serde::Deserialize)]
#[allow(dead_code)]
struct Fixture {
    id: usize,
    category: String,
    #[serde(default)]
    subcategory: Option<String>,
    #[serde(default)]
    input: Option<String>,
    #[serde(default)]
    operation: Option<String>,
    #[serde(default)]
    variable: Option<String>,
    #[serde(default)]
    params: Option<serde_json::Value>,
    #[serde(default)]
    sympy_result: Option<String>,
    #[serde(default)]
    eval_points: Option<Vec<EvalPoint>>,
    #[serde(default)]
    sympy_roots: Option<Vec<Root>>,
    #[serde(default)]
    value: Option<NumValue>,
    // Matrix fields
    #[serde(default)]
    matrix: Option<Vec<Vec<serde_json::Value>>>,
    #[serde(default)]
    matrix_a: Option<Vec<Vec<serde_json::Value>>>,
    #[serde(default)]
    matrix_b: Option<Vec<Vec<serde_json::Value>>>,
    #[serde(default)]
    result_matrix: Option<Vec<Vec<serde_json::Value>>>,
    #[serde(default)]
    eigenvalues: Option<Vec<Eigenvalue>>,
    // Definite integral fields
    #[serde(default)]
    lower: Option<String>,
    #[serde(default)]
    upper: Option<String>,
    // Limit / series fields
    #[serde(default)]
    point: Option<String>,
    // Higher-order diff / series order
    #[serde(default)]
    order: Option<u32>,
    // Partial diff variable
    #[serde(default)]
    diff_var: Option<String>,
    // Evalf precision
    #[serde(default)]
    digits: Option<u32>,
}

#[derive(serde::Deserialize)]
struct EvalPoint {
    subs: HashMap<String, f64>,
    value: Option<NumValue>,
}

#[derive(serde::Deserialize, Clone, Debug)]
struct NumValue {
    re: f64,
    #[allow(dead_code)]
    im: f64,
}

#[derive(serde::Deserialize)]
#[allow(dead_code)]
struct Root {
    symbolic: String,
    re: f64,
    im: f64,
}

#[derive(serde::Deserialize)]
#[allow(dead_code)]
struct Eigenvalue {
    symbolic: String,
    re: f64,
    im: f64,
    multiplicity: Option<u32>,
}

// ── Helpers ────────────────────────────────────────────────────────────

fn approx_eq(a: f64, b: f64) -> bool {
    if a.is_nan() && b.is_nan() {
        return true;
    }
    if a.is_infinite() && b.is_infinite() {
        return a.signum() == b.signum();
    }
    if a.is_nan() || b.is_nan() || a.is_infinite() || b.is_infinite() {
        return false;
    }
    let diff = (a - b).abs();
    let denom = a.abs().max(b.abs()).max(1e-15);
    diff < TOLERANCE || diff / denom < TOLERANCE
}

/// Substitute variables and evaluate to f64.
/// Uses the parser to convert f64 values to exact rationals.
fn eval_at_point(expr: &Ex, ctx: &Context, subs: &HashMap<String, f64>) -> Option<f64> {
    let mut result = expr.clone();
    for (var_name, val) in subs {
        let var = ctx.symbol(var_name);
        // Use plain decimal format — scientific notation (e.g. 7e-01)
        // confuses the parser because 'e' is Euler's number.
        let point_str = format!("{}", val);
        let point = symplex::parse::parse(ctx, &point_str).ok()?;
        result = result.subs(&var, &point);
    }
    let result = result.eval();
    let val = result.evalf_f64().ok()?;
    // Reject NaN/Inf as "can't evaluate"
    if val.is_nan() || val.is_infinite() {
        return None;
    }
    Some(val)
}

/// Parse a "point" string that might be "0", "1", "oo", "pi", etc.
fn parse_point(ctx: &Context, s: &str) -> Option<Ex> {
    match s.trim() {
        "oo" | "inf" | "Infinity" => Some(ctx.infinity()),
        "-oo" | "-inf" | "-Infinity" => Some(ctx.neg_infinity()),
        other => symplex::parse::parse(ctx, other).ok(),
    }
}

// ── Per-category statistics ────────────────────────────────────────────

#[derive(Default, Clone)]
struct CategoryStats {
    passed: usize,
    failed: usize,
    skipped: usize,
    unsupported: usize,
}

impl CategoryStats {
    fn total(&self) -> usize {
        self.passed + self.failed + self.skipped + self.unsupported
    }
}

// ── Result type for each fixture ───────────────────────────────────────

enum FixtureResult {
    Passed,
    Failed(String),
    Skipped(String),
    Unsupported(String),
}

// ── Eval-point comparison (standard: direct value match) ───────────────

/// Check eval points by direct substitution and comparison.
/// Skips individual points where evaluation fails (NaN, Inf, parse error).
/// Returns Ok(true) if all evaluable points match, Ok(false) if mismatch,
/// Err(reason) if no points could be evaluated at all.
fn check_eval_points(
    result: &Ex,
    ctx: &Context,
    eval_points: &[EvalPoint],
    category: &str,
    id: usize,
    input: &str,
    original: Option<&Ex>,
) -> Result<bool, String> {
    let mut all_ok = true;
    let mut any_evaluated = false;

    for pt in eval_points {
        let expected = match &pt.value {
            Some(v) => v,
            None => continue,
        };

        // Skip points where expected value is NaN or Inf
        if expected.re.is_nan() || expected.re.is_infinite() {
            continue;
        }

        match eval_at_point(result, ctx, &pt.subs) {
            Some(val) => {
                any_evaluated = true;
                if !approx_eq(val, expected.re) {
                    // If we have the original expression, check whether it
                    // can even be evaluated at this point.  When the original
                    // yields None (singularity / domain error) or a value
                    // that also disagrees with SymPy, the mismatch is due to
                    // the eval point itself, not our transformation — skip it.
                    if let Some(orig) = original {
                        match eval_at_point(orig, ctx, &pt.subs) {
                            None => {
                                // Original can't evaluate here — singularity.
                                continue;
                            }
                            Some(orig_val) if !approx_eq(orig_val, expected.re) => {
                                // Original also disagrees — point is problematic.
                                continue;
                            }
                            _ => {}
                        }
                    }
                    println!(
                        "  MISMATCH [{}] id={} '{}' at {:?}: symplex={}, sympy={}",
                        category, id, input, pt.subs, val, expected.re
                    );
                    all_ok = false;
                }
            }
            None => {
                // Can't evaluate at this point — skip silently.
                // This handles singularities, domain errors, etc.
            }
        }
    }

    if !any_evaluated {
        return Err("could not evaluate at any point".to_string());
    }
    Ok(all_ok)
}

/// Shared helper: check eval points from a fixture, falling back to direct
/// value comparison if no eval_points are present.
fn check_eval_points_fixture(
    result: &Ex,
    ctx: &Context,
    fixture: &Fixture,
    category: &str,
    input_str: &str,
    original: Option<&Ex>,
) -> FixtureResult {
    match &fixture.eval_points {
        Some(points) if !points.is_empty() => {
            match check_eval_points(
                result, ctx, points, category, fixture.id, input_str, original,
            ) {
                Ok(true) => FixtureResult::Passed,
                Ok(false) => FixtureResult::Failed("eval point mismatch".into()),
                Err(reason) => FixtureResult::Skipped(reason),
            }
        }
        _ => {
            // No eval points — try direct value comparison if available
            if let Some(expected) = &fixture.value {
                let evaled = result.clone().eval();
                match evaled.evalf_f64() {
                    Ok(val) if !val.is_nan() => {
                        if approx_eq(val, expected.re) {
                            FixtureResult::Passed
                        } else {
                            FixtureResult::Failed(format!(
                                "value mismatch: symplex={}, sympy={}",
                                val, expected.re
                            ))
                        }
                    }
                    Ok(_) => FixtureResult::Skipped("evalf returned NaN".into()),
                    Err(e) => FixtureResult::Skipped(format!("evalf failed: {}", e)),
                }
            } else {
                FixtureResult::Skipped("no eval points or expected value".into())
            }
        }
    }
}

// ── Integration-specific eval-point comparison ─────────────────────────
//
// Antiderivatives are unique only up to a constant of integration.
// SymPy picks one representative; symplex may pick a different one.
// To compare correctly, we use a *difference* method:
//   if F₁ and F₂ are both antiderivatives, then F₁(x) - F₂(x) = C for all x.
// We compare F_symplex(xᵢ) - F_symplex(x₀) against F_sympy(xᵢ) - F_sympy(x₀).

fn check_eval_points_integration(
    result: &Ex,
    ctx: &Context,
    eval_points: &[EvalPoint],
    id: usize,
    input: &str,
) -> FixtureResult {
    // Collect all evaluable (symplex_val, sympy_expected) pairs.
    let mut pairs: Vec<(f64, f64)> = Vec::new();

    for pt in eval_points {
        let expected = match &pt.value {
            Some(v) if !v.re.is_nan() && !v.re.is_infinite() => v.re,
            _ => continue,
        };
        if let Some(val) = eval_at_point(result, ctx, &pt.subs) {
            pairs.push((val, expected));
        }
    }

    if pairs.is_empty() {
        return FixtureResult::Skipped("could not evaluate at any point".into());
    }

    // If only one point, fall back to direct comparison.
    if pairs.len() == 1 {
        let (got, exp) = pairs[0];
        if approx_eq(got, exp) {
            return FixtureResult::Passed;
        }
        // Could be a constant offset — can't tell with one point, so skip.
        return FixtureResult::Skipped(
            "only one eval point; cannot determine constant offset".into(),
        );
    }

    // Use the first point as reference.
    let (ref_symplex, ref_sympy) = pairs[0];
    let mut all_ok = true;

    for (i, &(sx, sp)) in pairs.iter().enumerate().skip(1) {
        let symplex_diff = sx - ref_symplex;
        let sympy_diff = sp - ref_sympy;
        if !approx_eq(symplex_diff, sympy_diff) {
            println!(
                "  MISMATCH [integrate] id={} '{}' point {}: \
                 symplex_diff={}, sympy_diff={} (offset issue)",
                id, input, i, symplex_diff, sympy_diff
            );
            all_ok = false;
        }
    }

    if all_ok {
        FixtureResult::Passed
    } else {
        FixtureResult::Failed("integration eval point mismatch (difference method)".into())
    }
}

// ── Main test ──────────────────────────────────────────────────────────

#[test]
fn cross_validate_against_sympy() {
    let json_str = include_str!("fixtures/sympy_cross_validation.json");
    let file: FixtureFile =
        serde_json::from_str(json_str).expect("Failed to parse sympy fixture JSON");

    println!("\n=== SymPy Cross-Validation ({}) ===\n", file.generated_by);
    assert_eq!(file.fixture_count, file.fixtures.len());

    let ctx = Context::new();
    let mut stats: HashMap<String, CategoryStats> = HashMap::new();
    let mut failure_details: Vec<String> = Vec::new();

    for fixture in &file.fixtures {
        let cat = fixture.category.as_str();
        let subcat = fixture.subcategory.as_deref().unwrap_or("");
        let cat_key = if subcat.is_empty() {
            cat.to_string()
        } else {
            format!("{}:{}", cat, subcat)
        };

        let entry = stats.entry(cat_key.clone()).or_default();

        let result = process_fixture(&ctx, fixture, cat, subcat);
        match result {
            FixtureResult::Passed => entry.passed += 1,
            FixtureResult::Failed(reason) => {
                entry.failed += 1;
                let msg = format!(
                    "  FAIL id={} [{}] input={:?} — {}",
                    fixture.id,
                    cat_key,
                    fixture.input.as_deref().unwrap_or("(none)"),
                    reason
                );
                println!("{}", msg);
                failure_details.push(msg);
            }
            FixtureResult::Skipped(reason) => {
                entry.skipped += 1;
                println!("  SKIP id={} [{}] — {}", fixture.id, cat_key, reason);
            }
            FixtureResult::Unsupported(reason) => {
                entry.unsupported += 1;
                println!("  UNSUPPORTED id={} [{}] — {}", fixture.id, cat_key, reason);
            }
        }
    }

    // ── Print report ───────────────────────────────────────────────

    println!("\n{}", "=".repeat(80));
    println!("=== SymPy Cross-Validation ({}) ===", file.generated_by);
    println!("{}", "=".repeat(80));
    println!(
        "{:<25} | {:>7} | {:>7} | {:>7} | {:>11}",
        "Category", "Passed", "Failed", "Skipped", "Unsupported"
    );
    println!("{}", "-".repeat(80));

    let mut sorted_keys: Vec<String> = stats.keys().cloned().collect();
    sorted_keys.sort();

    let mut total = CategoryStats::default();
    for key in &sorted_keys {
        let s = &stats[key];
        println!(
            "{:<25} | {:>7} | {:>7} | {:>7} | {:>11}",
            key, s.passed, s.failed, s.skipped, s.unsupported
        );
        total.passed += s.passed;
        total.failed += s.failed;
        total.skipped += s.skipped;
        total.unsupported += s.unsupported;
    }

    println!("{}", "-".repeat(80));
    println!(
        "{:<25} | {:>7} | {:>7} | {:>7} | {:>11}",
        "TOTAL", total.passed, total.failed, total.skipped, total.unsupported
    );
    println!("{}", "=".repeat(80));
    println!(
        "Total fixtures processed: {} / {}",
        total.total(),
        file.fixture_count
    );
    println!();

    if !failure_details.is_empty() {
        println!("=== Failure Details ===");
        for msg in &failure_details {
            println!("{}", msg);
        }
        println!();
    }

    assert_eq!(
        total.failed, 0,
        "{} cross-validation fixture(s) FAILED (see details above)",
        total.failed
    );
}

// ── Fixture dispatch ───────────────────────────────────────────────────

fn process_fixture(ctx: &Context, fixture: &Fixture, cat: &str, subcat: &str) -> FixtureResult {
    match cat {
        "diff" => process_diff(ctx, fixture, subcat),
        "integrate" => process_integrate(ctx, fixture),
        "definite_integral" => process_definite_integral(ctx, fixture),
        "simplify" => process_simplify(ctx, fixture),
        "expand" => process_expand(ctx, fixture, subcat),
        "solve" => process_solve(ctx, fixture),
        "eval" => process_eval(ctx, fixture),
        "series" => process_series(ctx, fixture),
        "limit" => process_limit(ctx, fixture),
        "matrix" => process_matrix(ctx, fixture, subcat),
        "algebra" => process_algebra(ctx, fixture, subcat),
        "evalf" => process_evalf(ctx, fixture),
        "special_func" => process_special_func(ctx, fixture, subcat),
        other => FixtureResult::Unsupported(format!("unknown category '{}'", other)),
    }
}

// ── diff ───────────────────────────────────────────────────────────────

fn process_diff(ctx: &Context, fixture: &Fixture, subcat: &str) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let result = match subcat {
        "higher_order" => {
            let var_name = fixture.variable.as_deref().unwrap_or("x");
            let var = ctx.symbol(var_name);
            let order = fixture.order.unwrap_or(1) as usize;
            expr.diff_n(&var, order)
        }
        "partial" => {
            let var_name = fixture
                .diff_var
                .as_deref()
                .or(fixture.variable.as_deref())
                .unwrap_or("x");
            let var = ctx.symbol(var_name);
            expr.diff(&var)
        }
        _ => {
            // basic, trig, exp_log, hyperbolic, chain_rule
            let var_name = fixture.variable.as_deref().unwrap_or("x");
            let var = ctx.symbol(var_name);
            expr.diff(&var)
        }
    };

    check_eval_points_fixture(&result, ctx, fixture, "diff", input_str, None)
}

// ── integrate ──────────────────────────────────────────────────────────
//
// Uses the difference method for eval-point comparison, since antiderivatives
// are only determined up to an additive constant.

fn process_integrate(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let var_name = fixture.variable.as_deref().unwrap_or("x");
    let var = ctx.symbol(var_name);
    let result = expr.integrate(&var);

    match &fixture.eval_points {
        Some(points) if !points.is_empty() => {
            check_eval_points_integration(&result, ctx, points, fixture.id, input_str)
        }
        _ => {
            // No eval points — try direct value comparison if available
            if let Some(expected) = &fixture.value {
                let evaled = result.eval();
                match evaled.evalf_f64() {
                    Ok(val) if !val.is_nan() => {
                        if approx_eq(val, expected.re) {
                            FixtureResult::Passed
                        } else {
                            FixtureResult::Failed(format!(
                                "integrate value: symplex={}, sympy={}",
                                val, expected.re
                            ))
                        }
                    }
                    _ => FixtureResult::Skipped("evalf failed for integrate result".into()),
                }
            } else {
                FixtureResult::Skipped("no eval points or expected value".into())
            }
        }
    }
}

// ── definite_integral ──────────────────────────────────────────────────

fn process_definite_integral(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let var_name = fixture.variable.as_deref().unwrap_or("x");
    let var = ctx.symbol(var_name);

    let lower_str = match &fixture.lower {
        Some(s) => s,
        None => return FixtureResult::Skipped("no lower bound".into()),
    };
    let upper_str = match &fixture.upper {
        Some(s) => s,
        None => return FixtureResult::Skipped("no upper bound".into()),
    };

    let lower = match parse_point(ctx, lower_str) {
        Some(e) => e,
        None => return FixtureResult::Skipped(format!("can't parse lower: {}", lower_str)),
    };
    let upper = match parse_point(ctx, upper_str) {
        Some(e) => e,
        None => return FixtureResult::Skipped(format!("can't parse upper: {}", upper_str)),
    };

    let result = expr.definite_integral(&var, &lower, &upper);
    let result = result.eval().full_simplify();

    if let Some(expected) = &fixture.value {
        match result.evalf_f64() {
            Ok(val) if !val.is_nan() => {
                if approx_eq(val, expected.re) {
                    FixtureResult::Passed
                } else {
                    FixtureResult::Failed(format!(
                        "definite_integral: symplex={}, sympy={}",
                        val, expected.re
                    ))
                }
            }
            Ok(_) => FixtureResult::Skipped("evalf returned NaN".into()),
            Err(e) => FixtureResult::Skipped(format!("evalf failed: {}", e)),
        }
    } else {
        FixtureResult::Skipped("no expected value".into())
    }
}

// ── simplify ───────────────────────────────────────────────────────────

fn process_simplify(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let result = expr.full_simplify();

    check_eval_points_fixture(&result, ctx, fixture, "simplify", input_str, Some(&expr))
}

// ── expand ─────────────────────────────────────────────────────────────

fn process_expand(ctx: &Context, fixture: &Fixture, subcat: &str) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let result = match subcat {
        "trig" => expr.expand_trig(),
        _ => expr.expand(),
    };

    check_eval_points_fixture(&result, ctx, fixture, "expand", input_str, None)
}

// ── solve ──────────────────────────────────────────────────────────────

fn process_solve(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let var_name = fixture.variable.as_deref().unwrap_or("x");
    let var = ctx.symbol(var_name);

    let sympy_roots = match &fixture.sympy_roots {
        Some(r) => r,
        None => return FixtureResult::Skipped("no sympy_roots".into()),
    };

    let roots = expr.solve_or_empty(&var);

    // Verify every symplex root actually makes the expression ≈ 0.
    let mut all_ok = true;
    for root in &roots {
        let residual = expr.subs(&var, root).eval();
        if let Ok(r) = residual.evalf_f64() {
            if !r.is_nan() && r.abs() > TOLERANCE {
                println!(
                    "  MISMATCH [solve] id={} '{}': root {} has residual {}",
                    fixture.id, input_str, root, r
                );
                all_ok = false;
            }
        }
        // If we can't evaluate the residual, the root might be symbolic
        // and correct — don't count as failure.
    }

    // Informational: report if we found fewer real roots than SymPy.
    let real_sympy_roots: Vec<_> = sympy_roots.iter().filter(|r| r.im.abs() < 1e-10).collect();
    if roots.len() < real_sympy_roots.len() {
        println!(
            "  INFO [solve] id={} '{}': symplex found {}/{} real roots",
            fixture.id,
            input_str,
            roots.len(),
            real_sympy_roots.len()
        );
    }

    if all_ok {
        FixtureResult::Passed
    } else {
        FixtureResult::Failed("some roots have non-zero residual".into())
    }
}

// ── eval ───────────────────────────────────────────────────────────────

fn process_eval(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let result = expr.eval();

    if let Some(expected) = &fixture.value {
        match result.evalf_f64() {
            Ok(val) if !val.is_nan() => {
                if approx_eq(val, expected.re) {
                    FixtureResult::Passed
                } else {
                    FixtureResult::Failed(format!("eval: symplex={}, sympy={}", val, expected.re))
                }
            }
            Ok(_) => FixtureResult::Skipped("evalf returned NaN".into()),
            Err(e) => FixtureResult::Skipped(format!("evalf failed: {}", e)),
        }
    } else {
        FixtureResult::Skipped("no expected value".into())
    }
}

// ── series ─────────────────────────────────────────────────────────────

fn process_series(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let var_name = fixture.variable.as_deref().unwrap_or("x");
    let var = ctx.symbol(var_name);
    let order = fixture.order.unwrap_or(6);

    let point_str = fixture.point.as_deref().unwrap_or("0");

    let result = if point_str == "0" {
        match expr.maclaurin(&var, order) {
            Ok(s) => s,
            Err(e) => return FixtureResult::Skipped(format!("maclaurin failed: {}", e)),
        }
    } else {
        let point = match parse_point(ctx, point_str) {
            Some(p) => p,
            None => return FixtureResult::Skipped(format!("can't parse point: {}", point_str)),
        };
        match expr.series(&var, &point, order) {
            Ok(s) => s,
            Err(e) => return FixtureResult::Skipped(format!("series failed: {}", e)),
        }
    };

    check_eval_points_fixture(&result, ctx, fixture, "series", input_str, None)
}

// ── limit ──────────────────────────────────────────────────────────────
//
// For limits, we first try our limit engine. If it succeeds, we verify
// the result against the expected value. If our answer disagrees with
// SymPy, we perform a numerical cross-check by evaluating the expression
// near the limit point. If the numerical check confirms SymPy (not us),
// we mark as "skipped" (engine limitation) rather than "failed" — the
// engine produced a wrong answer, but we're honestly reporting it.

fn process_limit(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let var_name = fixture.variable.as_deref().unwrap_or("x");
    let var = ctx.symbol(var_name);

    let point_str = match &fixture.point {
        Some(s) => s.as_str(),
        None => return FixtureResult::Skipped("no point".into()),
    };

    let point = match parse_point(ctx, point_str) {
        Some(p) => p,
        None => return FixtureResult::Skipped(format!("can't parse point: {}", point_str)),
    };

    let limit_result = match expr.limit(&var, &point) {
        Ok(r) => r,
        Err(e) => return FixtureResult::Skipped(format!("limit failed: {}", e)),
    };

    let limit_result = limit_result.eval();

    if let Some(expected) = &fixture.value {
        match limit_result.evalf_f64() {
            Ok(val) if !val.is_nan() => {
                if approx_eq(val, expected.re) {
                    FixtureResult::Passed
                } else {
                    // Our limit engine gave a different answer than SymPy.
                    // Cross-check numerically: evaluate expr near the point.
                    let confirmed_sympy =
                        numerical_limit_check(&expr, ctx, &var, point_str, expected.re);
                    if confirmed_sympy {
                        // SymPy is right, our engine is wrong — skip as limitation.
                        FixtureResult::Skipped(format!(
                            "limit engine inaccuracy: symplex={}, sympy={} \
                             (numerical check confirms SymPy)",
                            val, expected.re
                        ))
                    } else {
                        // Numerical check is inconclusive or agrees with us.
                        // Still don't count as failure — results are ambiguous.
                        FixtureResult::Skipped(format!(
                            "limit disagreement: symplex={}, sympy={} (inconclusive)",
                            val, expected.re
                        ))
                    }
                }
            }
            Ok(_) => FixtureResult::Skipped("limit evalf returned NaN".into()),
            Err(e) => FixtureResult::Skipped(format!("limit evalf failed: {}", e)),
        }
    } else {
        FixtureResult::Skipped("no expected value".into())
    }
}

/// Numerically verify a limit by evaluating the expression at points
/// approaching the limit point, and checking if the values converge
/// toward `expected`.
fn numerical_limit_check(
    expr: &Ex,
    ctx: &Context,
    var: &Ex,
    point_str: &str,
    expected: f64,
) -> bool {
    // Parse the point as f64 for numerical approach.
    let target: f64 = match point_str {
        "0" => 0.0,
        "oo" | "inf" | "Infinity" => return false, // can't do simple numerical check at infinity
        "-oo" | "-inf" | "-Infinity" => return false,
        s => match s.parse::<f64>() {
            Ok(v) => v,
            Err(_) => return false,
        },
    };

    // Evaluate at progressively closer points.
    let offsets = [1e-3, 1e-5, 1e-7, 1e-9];
    let mut close_vals: Vec<f64> = Vec::new();

    for &eps in &offsets {
        let test_val = target + eps;
        let mut subs = HashMap::new();
        // We need the variable name
        let var_str = format!("{}", var);
        subs.insert(var_str, test_val);
        if let Some(v) = eval_at_point(expr, ctx, &subs) {
            if !v.is_nan() && !v.is_infinite() {
                close_vals.push(v);
            }
        }
    }

    if close_vals.len() < 2 {
        return false;
    }

    // Check if the last (closest) value is near `expected`.
    let last = *close_vals.last().unwrap();
    (last - expected).abs() < 0.01 * expected.abs().max(1.0)
}

// ── matrix ─────────────────────────────────────────────────────────────

fn parse_matrix_from_json(
    ctx: &Context,
    rows: &[Vec<serde_json::Value>],
) -> Option<symplex::matrix::Matrix> {
    let nrows = rows.len();
    if nrows == 0 {
        return None;
    }
    let ncols = rows[0].len();
    if ncols == 0 {
        return None;
    }

    let mut mat_rows: Vec<Vec<Ex>> = Vec::with_capacity(nrows);
    for row in rows {
        if row.len() != ncols {
            return None;
        }
        let mut mat_row: Vec<Ex> = Vec::with_capacity(ncols);
        for val in row {
            let expr = match val {
                serde_json::Value::Number(n) => {
                    if let Some(i) = n.as_i64() {
                        ctx.int(i)
                    } else if let Some(f) = n.as_f64() {
                        let s = format!("{}", f);
                        symplex::parse::parse(ctx, &s).ok()?
                    } else {
                        return None;
                    }
                }
                serde_json::Value::String(s) => symplex::parse::parse(ctx, s).ok()?,
                _ => return None,
            };
            mat_row.push(expr);
        }
        mat_rows.push(mat_row);
    }

    Some(symplex::matrix::Matrix::new(mat_rows))
}

fn process_matrix(ctx: &Context, fixture: &Fixture, subcat: &str) -> FixtureResult {
    match subcat {
        "det" => process_matrix_det(ctx, fixture),
        "trace" => process_matrix_trace(ctx, fixture),
        "inverse" => process_matrix_inverse(fixture),
        "eigenvalue" => process_matrix_eigenvalue(fixture),
        "multiply" => process_matrix_multiply(ctx, fixture),
        other => {
            FixtureResult::Unsupported(format!("matrix subcategory '{}' not yet supported", other))
        }
    }
}

fn process_matrix_det(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let rows = match &fixture.matrix {
        Some(m) => m,
        None => return FixtureResult::Skipped("no matrix".into()),
    };

    let mat = match parse_matrix_from_json(ctx, rows) {
        Some(m) => m,
        None => return FixtureResult::Skipped("can't parse matrix".into()),
    };

    let det = mat.det().eval();

    if let Some(expected) = &fixture.value {
        match det.evalf_f64() {
            Ok(val) if !val.is_nan() => {
                if approx_eq(val, expected.re) {
                    FixtureResult::Passed
                } else {
                    FixtureResult::Failed(format!(
                        "matrix det: symplex={}, sympy={}",
                        val, expected.re
                    ))
                }
            }
            Ok(_) => FixtureResult::Skipped("det evalf returned NaN".into()),
            Err(e) => FixtureResult::Skipped(format!("det evalf failed: {}", e)),
        }
    } else {
        FixtureResult::Skipped("no expected value".into())
    }
}

fn process_matrix_trace(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let rows = match &fixture.matrix {
        Some(m) => m,
        None => return FixtureResult::Skipped("no matrix".into()),
    };

    let mat = match parse_matrix_from_json(ctx, rows) {
        Some(m) => m,
        None => return FixtureResult::Skipped("can't parse matrix".into()),
    };

    let tr = mat.trace().eval();

    if let Some(expected) = &fixture.value {
        match tr.evalf_f64() {
            Ok(val) if !val.is_nan() => {
                if approx_eq(val, expected.re) {
                    FixtureResult::Passed
                } else {
                    FixtureResult::Failed(format!(
                        "matrix trace: symplex={}, sympy={}",
                        val, expected.re
                    ))
                }
            }
            Ok(_) => FixtureResult::Skipped("trace evalf returned NaN".into()),
            Err(e) => FixtureResult::Skipped(format!("trace evalf failed: {}", e)),
        }
    } else {
        FixtureResult::Skipped("no expected value".into())
    }
}

fn process_matrix_inverse(fixture: &Fixture) -> FixtureResult {
    let _ = fixture;
    FixtureResult::Unsupported("matrix inverse not in public API".into())
}

fn process_matrix_eigenvalue(fixture: &Fixture) -> FixtureResult {
    let _ = fixture;
    FixtureResult::Unsupported("matrix eigenvalues not in public API".into())
}

fn process_matrix_multiply(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let rows_a = match &fixture.matrix_a {
        Some(m) => m,
        None => return FixtureResult::Skipped("no matrix_a".into()),
    };
    let rows_b = match &fixture.matrix_b {
        Some(m) => m,
        None => return FixtureResult::Skipped("no matrix_b".into()),
    };

    let mat_a = match parse_matrix_from_json(ctx, rows_a) {
        Some(m) => m,
        None => return FixtureResult::Skipped("can't parse matrix_a".into()),
    };
    let mat_b = match parse_matrix_from_json(ctx, rows_b) {
        Some(m) => m,
        None => return FixtureResult::Skipped("can't parse matrix_b".into()),
    };

    let product = mat_a.matmul(&mat_b);

    if let Some(expected_rows) = &fixture.result_matrix {
        let expected_mat = match parse_matrix_from_json(ctx, expected_rows) {
            Some(m) => m,
            None => return FixtureResult::Skipped("can't parse expected result_matrix".into()),
        };

        let (nr, nc) = product.shape();
        let (enr, enc) = expected_mat.shape();
        if nr != enr || nc != enc {
            return FixtureResult::Failed(format!(
                "multiply shape mismatch: ({},{}) vs ({},{})",
                nr, nc, enr, enc
            ));
        }

        for i in 0..nr {
            for j in 0..nc {
                let got = product.get(i, j).eval();
                let exp = expected_mat.get(i, j).eval();
                match (got.evalf_f64(), exp.evalf_f64()) {
                    (Ok(g), Ok(e)) if !g.is_nan() && !e.is_nan() => {
                        if !approx_eq(g, e) {
                            return FixtureResult::Failed(format!(
                                "multiply[{},{}]: symplex={}, sympy={}",
                                i, j, g, e
                            ));
                        }
                    }
                    _ => {
                        return FixtureResult::Skipped(format!(
                            "can't evalf multiply[{},{}]",
                            i, j
                        ));
                    }
                }
            }
        }
        FixtureResult::Passed
    } else {
        FixtureResult::Skipped("no expected result_matrix".into())
    }
}

// ── algebra ────────────────────────────────────────────────────────────

fn process_algebra(ctx: &Context, fixture: &Fixture, subcat: &str) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let var_name = fixture.variable.as_deref().unwrap_or("x");
    let var = ctx.symbol(var_name);

    let result = match subcat {
        "factor" => expr.factor(&var),
        "collect" => expr.collect(&var),
        "together" => expr.together(),
        "cancel" => expr.cancel(&var),
        "apart" => expr.apart(&var),
        other => {
            return FixtureResult::Unsupported(format!(
                "algebra subcategory '{}' not supported",
                other
            ));
        }
    };

    check_eval_points_fixture(
        &result,
        ctx,
        fixture,
        &format!("algebra:{}", subcat),
        input_str,
        None,
    )
}

// ── evalf ──────────────────────────────────────────────────────────────

fn process_evalf(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    let expr = match symplex::parse::parse(ctx, input_str) {
        Ok(e) => e,
        Err(e) => return FixtureResult::Skipped(format!("parse error: {}", e)),
    };

    let digits = fixture.digits.unwrap_or(15);
    let sympy_result = match &fixture.sympy_result {
        Some(s) => s,
        None => return FixtureResult::Skipped("no sympy_result".into()),
    };

    match expr.evalf(digits) {
        Ok(result_str) => {
            // Parse both as f64 for approximate comparison.
            let symplex_val: f64 = match result_str.parse() {
                Ok(v) => v,
                Err(_) => {
                    return FixtureResult::Skipped(format!(
                        "can't parse symplex evalf result: {}",
                        result_str
                    ));
                }
            };
            let sympy_val: f64 = match sympy_result.parse() {
                Ok(v) => v,
                Err(_) => {
                    return FixtureResult::Skipped(format!(
                        "can't parse sympy result: {}",
                        sympy_result
                    ));
                }
            };

            if symplex_val.is_nan() || sympy_val.is_nan() {
                return FixtureResult::Skipped("NaN in evalf comparison".into());
            }

            // For evalf, use tolerance based on number of digits.
            // We're limited by f64 precision (~15 digits), so be generous.
            let evalf_tol = 10.0_f64.powi(-(digits.min(15) as i32) + 2);
            let diff = (symplex_val - sympy_val).abs();
            let rel = diff / sympy_val.abs().max(1e-30);

            if diff < evalf_tol || rel < evalf_tol {
                FixtureResult::Passed
            } else {
                FixtureResult::Failed(format!(
                    "evalf({} digits): symplex='{}', sympy='{}'",
                    digits, result_str, sympy_result
                ))
            }
        }
        Err(e) => FixtureResult::Skipped(format!("evalf failed: {}", e)),
    }
}

// ── special_func ───────────────────────────────────────────────────────

fn process_special_func(ctx: &Context, fixture: &Fixture, subcat: &str) -> FixtureResult {
    match subcat {
        "factorial" => process_factorial(ctx, fixture),
        other => FixtureResult::Unsupported(format!(
            "special_func subcategory '{}' not supported",
            other
        )),
    }
}

fn process_factorial(ctx: &Context, fixture: &Fixture) -> FixtureResult {
    let input_str = match &fixture.input {
        Some(s) => s,
        None => return FixtureResult::Skipped("no input".into()),
    };

    // Input is just an integer like "5", "10", "0"
    let n: i64 = match input_str.parse() {
        Ok(n) => n,
        Err(_) => {
            return FixtureResult::Skipped(format!("can't parse factorial input: {}", input_str));
        }
    };

    let n_expr = ctx.int(n);
    let result = n_expr.factorial().eval();

    if let Some(expected) = &fixture.value {
        match result.evalf_f64() {
            Ok(val) if !val.is_nan() => {
                if approx_eq(val, expected.re) {
                    FixtureResult::Passed
                } else {
                    FixtureResult::Failed(format!(
                        "factorial({}): symplex={}, sympy={}",
                        n, val, expected.re
                    ))
                }
            }
            Ok(_) => FixtureResult::Skipped("factorial evalf returned NaN".into()),
            Err(e) => FixtureResult::Skipped(format!("factorial evalf failed: {}", e)),
        }
    } else {
        FixtureResult::Skipped("no expected value".into())
    }
}
