//! Consumer for `tests/fixtures/new_features_cross_validation.json`
//! (generated by `scripts/gen_new_fixtures.py`): eigenvectors, Jordan form,
//! LambertW, Bessel functions, `refine`, inverse-hyperbolic antiderivatives,
//! erf special values, and matrix exponentials.
//!
//! Previously this fixture file had no consumer at all; it now follows the
//! same honesty policy as the rest of the 0.2 oracle (see
//! `v02_oracle_common/mod.rs`).  One `#[test]` per category.

use super::v02_oracle_common;

use std::sync::OnceLock;

use serde_json::Value;
use symplex::prelude::*;
use v02_oracle_common::*;

const TOL: f64 = 1e-9;

/// Library bugs surfaced by this file (strict xfail — see common module).
/// Subcategory `"*"` matches any subcategory of the category.
const KNOWN_BUGS: &[KnownBug] = &[];

/// Regression for the large-argument Bessel bug (fixed: the Hankel `P/Q`
/// expansion double-counted `a_0` and switched on too early).
/// SymPy: J0(20) = 0.16702466434058315.
#[test]
fn bug_besselj_large_argument() {
    let ctx = Context::new();
    let v = ctx.int(20).bessel_j(&ctx.int(0)).eval_f64().unwrap();
    assert!((v - 0.16702466434058315).abs() < 1e-10, "J0(20) = {v}");
    let y = ctx.int(30).bessel_y(&ctx.int(0)).eval_f64().unwrap();
    assert!((y + 0.11729573168666402).abs() < 1e-10, "Y0(30) = {y}");
}

static NEW_FEATURES: OnceLock<(String, Vec<Fixture>)> = OnceLock::new();

fn file() -> &'static (String, Vec<Fixture>) {
    NEW_FEATURES.get_or_init(|| {
        #[derive(serde::Deserialize)]
        struct File {
            generated_by: String,
            fixture_count: usize,
            fixtures: Vec<Fixture>,
        }
        let f: File = serde_json::from_str(include_str!(
            "../fixtures/new_features_cross_validation.json"
        ))
        .expect("new_features fixture JSON must parse");
        assert_eq!(f.fixture_count, f.fixtures.len());
        (f.generated_by, f.fixtures)
    })
}

/// Same policy as `v02_oracle_common::run`, over this file's fixtures
/// (one `#[test]` per category; keys are unique within a category).
fn run_category(
    category: &str,
    process: impl Fn(&Context, &Fixture) -> Status + Send + Sync + 'static,
) {
    let (generated_by, fixtures) = file();
    run_fixtures(fixtures, generated_by, category, None, KNOWN_BUGS, process);
}

fn matrix_in(ctx: &Context, fx: &Fixture) -> Result<Matrix, Status> {
    parse_matrix(ctx, fx, "input_matrix").map_err(Status::NotImplemented)
}

#[test]
fn new_features_eigenvects() {
    run_category("eigenvects", |ctx, fx| {
        let m = match matrix_in(ctx, fx) {
            Ok(m) => m,
            Err(s) => return s,
        };
        let want: Vec<((f64, f64), usize, usize)> = fx
            .field("eigenspaces")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .filter_map(|e| {
                        let Num::Finite(re, im) = Num::from_json(e.get("eigenvalue")?)? else {
                            return None;
                        };
                        Some((
                            (re, im),
                            e.get("algebraic_multiplicity")?.as_u64()? as usize,
                            e.get("geometric_multiplicity")?.as_u64()? as usize,
                        ))
                    })
                    .collect()
            })
            .unwrap_or_default();
        let got_raw = match m.eigenvects() {
            Ok(v) => v,
            Err(e) => return Status::NotImplemented(format!("{e}")),
        };
        let mut got: Vec<((f64, f64), usize, usize)> = Vec::new();
        for (val, mult, vecs) in &got_raw {
            let Ok(c) = val.eval_complex64() else {
                return Status::NotImplemented(format!("eigenvalue {} not numeric", truncate(val)));
            };
            // Each eigenvector must satisfy (A − λI)v = 0 and be nonzero.
            for v in vecs {
                let av = m.matmul(v).unwrap_or_else(|e| panic!("{e}"));
                let lv = v.scale(val);
                let diff = av.sub(&lv).unwrap_or_else(|e| panic!("{e}"));
                match matrix_c64(&diff) {
                    Ok(rows) if rows.iter().flatten().all(|c| c.0.hypot(c.1) < 1e-9) => {}
                    Ok(_) => {
                        return Status::Fail(format!(
                            "A·v ≠ λ·v for λ={} v={:?}",
                            truncate(val),
                            matrix_c64(v)
                        ));
                    }
                    Err(e) => return Status::NotImplemented(e),
                }
                if matrix_c64(v).map(|r| r.iter().flatten().all(|c| c.0.hypot(c.1) < 1e-12))
                    == Ok(true)
                {
                    return Status::Fail(format!(
                        "zero eigenvector reported for λ={}",
                        truncate(val)
                    ));
                }
            }
            got.push((c, *mult, vecs.len()));
        }
        let key = |t: &((f64, f64), usize, usize)| {
            ((t.0.0 * 1e9).round() as i64, (t.0.1 * 1e9).round() as i64)
        };
        got.sort_by_key(key);
        let mut want = want;
        want.sort_by_key(key);
        if got.len() != want.len() {
            return Status::Fail(format!(
                "eigenspace count: symplex={} sympy={} ({got:?} vs {want:?})",
                got.len(),
                want.len()
            ));
        }
        for (g, w) in got.iter().zip(&want) {
            if !complex_matches(g.0, w.0, TOL) || g.1 != w.1 || g.2 != w.2 {
                return Status::Fail(format!("(λ, alg, geom): symplex={got:?} sympy={want:?}"));
            }
        }
        Status::Pass
    });
}

#[test]
fn new_features_jordan_form() {
    run_category("jordan_form", |ctx, fx| {
        let m = match matrix_in(ctx, fx) {
            Ok(m) => m,
            Err(s) => return s,
        };
        let (p, j) = match m.jordan_form() {
            Ok(v) => v,
            Err(e) => return Status::NotImplemented(format!("{e}")),
        };
        let jn = match matrix_c64(&j) {
            Ok(v) => v,
            Err(e) => return Status::NotImplemented(e),
        };
        let ones = (0..jn.len() - 1)
            .filter(|&i| jn[i][i + 1].0.hypot(jn[i][i + 1].1) > 1e-9)
            .count();
        if ones != fx.u64("superdiag_ones").unwrap_or(0) as usize {
            return Status::Fail(format!(
                "super-diagonal ones: symplex={ones} sympy={}",
                fx.u64("superdiag_ones").unwrap_or(0)
            ));
        }
        let diag: Vec<(f64, f64)> = (0..jn.len()).map(|i| jn[i][i]).collect();
        let want: Vec<Num> = fx
            .field("jordan_diag")
            .and_then(Value::as_array)
            .map(|a| a.iter().filter_map(Num::from_json).collect())
            .unwrap_or_default();
        let Some(want) = nums_to_complex(&want) else {
            return Status::SkippedOracle("non-finite oracle eigenvalue".into());
        };
        if let Status::Fail(r) = compare_complex_multisets(diag, want, TOL) {
            return Status::Fail(r);
        }
        let recon = p
            .matmul(&j)
            .and_then(|pj| pj.matmul(&p.inv()?))
            .unwrap_or_else(|e| panic!("{e}"))
            .simplify();
        if recon != m {
            return Status::Fail(format!("P·J·P⁻¹ ≠ A: got {recon}"));
        }
        Status::Pass
    });
}

#[test]
fn new_features_lambertw() {
    run_category("lambertw", |ctx, fx| {
        let arg = match parse(ctx, fx.str("input").unwrap_or("0")) {
            Ok(e) => e,
            Err(e) => return Status::NotImplemented(e),
        };
        let Some(want) = fx.num("value") else {
            return Status::SkippedOracle("no value".into());
        };
        let w = arg.lambertw().eval();
        let status = compare_constant(ctx, &w, &want, 1e-12);
        if !matches!(status, Status::Pass) {
            return status;
        }
        // Symbolic special values must fold exactly (W(0)=0, W(e)=1, W(-1/e)=-1).
        if fx.subcategory == "eval_symbolic"
            && let Some(expected) = fx.str("expected")
            && !expected.contains("LambertW")
            && w.to_string().contains("LambertW")
        {
            return Status::NotImplemented(format!(
                "special value not folded: {w} (SymPy: {expected})"
            ));
        }
        Status::Pass
    });
}

#[test]
fn new_features_bessel() {
    run_category("bessel", |ctx, fx| {
        let xv = match parse(ctx, fx.str("x").unwrap_or("0")) {
            Ok(e) => e,
            Err(e) => return Status::NotImplemented(e),
        };
        let order = ctx.int(fx.i64("order").unwrap_or(0));
        let Some(want) = fx.num("value") else {
            return Status::SkippedOracle("no value".into());
        };
        let r = match fx.str("kind") {
            Some("J") => xv.bessel_j(&order),
            Some("Y") => xv.bessel_y(&order),
            other => return Status::UnsupportedApi(format!("kind {other:?}")),
        };
        compare_constant(ctx, &r, &want, 1e-10)
    });
}

#[test]
fn new_features_refine() {
    run_category("refine", |ctx, fx| {
        let x = ctx.symbol("x");
        let assumption = match fx.str("assumptions") {
            Some("positive") => Assumption::Positive,
            Some("negative") => Assumption::Negative,
            Some("nonnegative") => Assumption::NonNegative,
            Some("zero") => Assumption::Zero,
            Some("real") => Assumption::Real,
            Some("integer") => Assumption::Integer,
            other => return Status::UnsupportedApi(format!("assumption {other:?}")),
        };
        let input = fx.str("input").unwrap_or("").replace("Abs(", "abs(");
        let e = match parse(ctx, &input) {
            Ok(e) => e,
            Err(e) => return Status::NotImplemented(e),
        };
        let r = e.refine_with(&[(&x, assumption)]);
        // Value must be preserved on the assumed domain …
        let status = compare_eval_points(ctx, &r, fx, "eval_points", TOL);
        if !matches!(status, Status::Pass) {
            return status;
        }
        // … and the refinement should be as tight as SymPy's.
        let want_ops = fx.u64("sympy_ops").unwrap_or(0) as usize;
        if r.count_ops() > want_ops {
            return Status::NotImplemented(format!(
                "value OK but not refined: {} vs SymPy {}",
                truncate(&r),
                fx.str("sympy_result").unwrap_or("?")
            ));
        }
        Status::Pass
    });
}

#[test]
fn new_features_integrate_inverse_hyperbolic() {
    run_category("integrate", |ctx, fx| {
        let f = match parse(ctx, fx.str("input").unwrap_or("")) {
            Ok(e) => e,
            Err(e) => return Status::NotImplemented(e),
        };
        let x = ctx.symbol("x");
        let big_f = match f.try_integrate(&x) {
            Ok(v) => v,
            Err(e) => return Status::NotImplemented(format!("{e}")),
        };
        // Antiderivatives agree up to a constant: compare differences.
        let pts = fx.eval_points("eval_points");
        let mut pairs = Vec::new();
        for pt in &pts {
            let Some(Num::Finite(w, _)) = pt.value else {
                continue;
            };
            match eval_at(&big_f, ctx, &pt.subs) {
                Some((g, _)) => pairs.push((g, w)),
                None => {
                    return Status::NotImplemented(format!("cannot evaluate {}", truncate(&big_f)));
                }
            }
        }
        if pairs.len() < 2 {
            return Status::SkippedOracle("need ≥ 2 eval points".into());
        }
        let (g0, w0) = pairs[0];
        for (g, w) in &pairs[1..] {
            if !approx_eq_tol(g - g0, w - w0, TOL) {
                return Status::Fail(format!(
                    "F differences disagree: symplex {} vs sympy {}",
                    g - g0,
                    w - w0
                ));
            }
        }
        // Also the derivative must reproduce the integrand.
        let back = big_f.diff(&x);
        for pt in &pts {
            let (Some(a), Some(b)) = (eval_at(&back, ctx, &pt.subs), eval_at(&f, ctx, &pt.subs))
            else {
                continue;
            };
            if !complex_matches(a, b, TOL) {
                return Status::Fail(format!("d/dx F ≠ f at {:?}: {a:?} vs {b:?}", pt.subs));
            }
        }
        Status::Pass
    });
}

#[test]
fn new_features_erf_special_values() {
    run_category("eval", |ctx, fx| {
        let e = match parse(ctx, fx.str("input").unwrap_or("")) {
            Ok(e) => e,
            Err(e) => return Status::NotImplemented(e),
        };
        let Some(want) = fx.num("value") else {
            return Status::SkippedOracle("no value".into());
        };
        compare_constant(ctx, &e.eval(), &want, 1e-12)
    });
}

#[test]
fn new_features_matrix_exp() {
    run_category("matrix_exp", |ctx, fx| {
        let m = match matrix_in(ctx, fx) {
            Ok(m) => m,
            Err(s) => return s,
        };
        let e = match m.matrix_exp() {
            Ok(e) => e,
            Err(err) => return Status::NotImplemented(format!("{err}")),
        };
        let Some(want) = parse_num_matrix(fx, "result_numeric") else {
            return Status::SkippedOracle("no result".into());
        };
        let got = match matrix_c64(&e) {
            Ok(g) => g,
            Err(err) => return Status::NotImplemented(err),
        };
        for (i, (gr, wr)) in got.iter().zip(&want).enumerate() {
            for (j, (g, w)) in gr.iter().zip(wr).enumerate() {
                let Num::Finite(re, im) = w else {
                    return Status::SkippedOracle("non-finite".into());
                };
                if !complex_matches(*g, (*re, *im), TOL) {
                    return Status::Fail(format!("exp(A)[{i},{j}] = {g:?}, SymPy ({re}, {im})"));
                }
            }
        }
        Status::Pass
    });
}
